### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by norb1969** [datatypevoid/vulgar-cli#1]
I had a couple of issues while installing and using vulgar-cli.
- Had to run dos2unix conversion on vulgar-cli js files in node_modules.  They had ^M line endings which was causing me problems on Ubuntu 15.10.
- Had to separately install generator-vulgar before running "vulgar init".

Once I'd done this I was up and running.  Hope this helps. Thanks!

**Comment by datatypevoid** [comment]
I'll have to look into the line ending problem. I thought I had it configured properly, but obviously not. I hop back and forth between `windows` and `ubuntu` a lot, so I'll take a look.

As far as installing `generator-vulgar`, that is normal. Most of the generation code is housed in `generator-vulgar` at this time. I am currently trying to figure out how to bring the generators into the `cli` cleanly. 

Thanks for pointing this out to me.

**Comment by datatypevoid** [comment]
Alright, thank you again for bringing this up. I still don't know what exactly is wrong with my `git` config, but `dos2unix` should serve fine to mitigate the problem while I work it out.

**Comment by datatypevoid** [comment]
Commmit fb464e2 should wrap this one up I believe.
