### ISSUE TITLE
vulgar init throws Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by CNSKnight** [datatypevoid/vulgar-cli#2]
I am using nvm and have tried several versions

```
$ vulgar init
? What would you have your MEAN app be called? mean

Checking permissions...

Cloning branch master into destination folder:  mean

git clone  --depth 1  -b master https://github.com/datatypevoid/vulgar.git "mean"

Cloning into 'mean'...

module.js:341
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/generator-vulgar/generators/config/index.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by datatypevoid** [comment]
Hey there @CNSKnight ! Sorry to hear you are having troubles with `nvm`. I regularly use `nvm` so we should be able to iron this out together. For starters, have you run `npm install` yet? If so, can you check that `lodash` is indeed installed?

**Comment by CNSKnight** [comment]
thanks D.
I did rerun my installs on a droplet I have and got a new project set up and ported back into my workspace, but the issue on local box still remains.

meantime, I'd even had lodash -g already but whatever there error is doesn't seem to find it.

some backstory: I had an apt version of node installed on the local linux box and then started using nvm which seems to be working fine. I since dropped the apt version, removed and reinstalled nvm, added libkrb5-dev to get vulgar to install but am left w/the above error and no complete init.

**Comment by datatypevoid** [comment]
Hmm I will have to try a fresh `ubuntu` box install with fresh `nvm` and `vulgar-cli` install tomorrow. I will let you know what I find.

**Comment by justasSav** [comment]
Having the same issue with npm. Windows 10

**Comment by justasSav** [comment]
`npm install -g lodash` solved it but it's not a proper fix eh?

**Comment by datatypevoid** [comment]
It is actually already fixed in the repo. The problem lies in the version that `npm` is delivering. 30 days ago I accepted a pull request fixing this issue, but forgot to bump the patch version and push the update to `npm`. I will address this immediately.

**Comment by CNSKnight** [comment]
Ok, I got a chance to circle back to this after resolving another unrelated. In my case I had to manually purge apt-get installed node following an nvm install/usage. Everything running groovy now, w/possible exception of "message: 'not authorized for query on vulgar-dev.users'" - but I'll research that later.
