### ISSUE TITLE
There are 2 files in your ~/.npm owned by root

### ISSUE THREAD

**Issue by slayerfat** [datatypevoid/vulgar-cli#4]
Greetings!

Im not sure if this a problem related to this repo or vulgar, however i can't init a new project, when i do `vulgar init name` there's an error:

```
vulgar init name
What would you have your MEAN app be called? name

Checking permissions...

Cloning branch master into destination folder:  name

git clone  --depth 1  -b master https://github.com/datatypevoid/vulgar.git "name"

/usr/bin/npm
Cloning into 'name'...
There are 2 files in your ~/.npm owned by root
Please change the permissions by running - chown -R `whoami` ~/.npm 

/home/thaurissan/npm-global/lib/node_modules/vulgar-cli/lib/install.js:84
      throw err;
      ^
Root permissions in ~/.npm

```

i already executed the `chown -R 'whoami' ~/.npm` command even as root, and still fails.

**Comment by datatypevoid** [comment]
Hey there! Sorry you're having trouble, but I'm sure we can figure this out. What `os`, `npm`, and `node` version are you using first off? Also, you didn't install with `sudo` did you?

**Comment by slayerfat** [comment]
oh sorry to mention that @datatypevoid 

i'm running ubuntu 16.04, npm 3.9.3 and node v6.2.1.

also i checked that indeed the npm folders are not related to root

**Comment by datatypevoid** [comment]
Pretty sure this is what fixed up that error for me: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

The `cli` won't work correctly with `root` owning `npm` which is what the error is stating, that there are two files in your npm directory owned by the `root` user. Let me know if this is helpful!

**Comment by slayerfat** [comment]
i already did the npm global without sudo (the global modules are owned by me) doing a `ls -lha -R ~/.npm/ | grep root` and `ls -lha -R ~/npm-global/ | grep root` (where the global install are) shows that no files are owned by root.

however, the npm bin is indeed owned by root

``` bash
/usr/bin/npm
lrwxrwxrwx 1 root root 38 jun  2 20:39 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

is the npm-cli required to be owned by me for vulgar-cli to run?

**Comment by datatypevoid** [comment]
Yeah everything must be owned by the owner trying to execute the command.

**Comment by slayerfat** [comment]
thank you very much @datatypevoid 

for future reference the solution for me was to change the npm symlink owner from root to me

**Comment by datatypevoid** [comment]
Glad everything worked out! Let me know if I can help with anything else.

**Comment by Pokom** [comment]
Is there anyway we can get this added to an FAQ? I know it's not specific to Vulgar, but this is the first time I've encountered this issue and spent ~1 hour before figuring it out. 

@slayerfat came through with a solid suggestion.

**Comment by datatypevoid** [comment]
Yeah, I'll make sure it gets added in, sorry about that! Glad you got it figured though! We're actually in the middle of a big refactor for all of the Angular 2 RC releases, but once the main pack is stabilized, it'll hit here as well.

**Comment by moosecodes** [comment]
I finally resolved this issue on my machine.  Running `chown -R <myusername> ~/.npm` was not good enough so I updated npm and node using the following commands:

Update npm: `npm install npm@latest -g`

Install n for npm to update node to latest version"
`sudo npm cache clean -f`
`sudo npm install -g n`
`sudo n stable`

My working configuration: MacOS Sierra, npm 3.10.9, node 7.0
