### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by hamzatrq** [datatypevoid/vulgar-cli#5]
Getting the following error. While `vulgar init mean2`

`? What would you have your MEAN app be called? mean2`

`Checking permissions...`

`Cloning branch master into destination folder:  mean2`

`git clone  --depth 1  -b master https://github.com/datatypevoid/vulgar.git "mean2"`

`/usr/bin/npm`
`There are 2 files in your ~/.npm owned by root`
`Please change the permissions by running - chown -R`whoami`~/.npm`

`/home/zeus/.npm-global/lib/node_modules/vulgar-cli/lib/install.js:84`
`throw err;`
`^`
`Root permissions in ~/.npm`

**Comment by datatypevoid** [comment]
Hey there, sorry it has taken so long for me to catch up with this issue. If you haven't fixed the issue yet, these guides should shed some light on the problem: 
- https://docs.npmjs.com/getting-started/fixing-npm-permissions
- https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

Let me know if this fixes your issue!

**Comment by datatypevoid** [comment]
Closing as this is not related to `vulgar-cli` but rather your `npm` configuration.
