### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by arcanewater** [datatypevoid/vulgar-cli#6]
Is this project still active? Based on badges a lot of dependencies are outdated?

**Comment by datatypevoid** [comment]
@arcanewater Yeah we're still chugging along. Right now there core pack is being brought up to date, and then the `cli` and `generator` will be updated to work with that. If you are interested in using a more up-to-date version of `vulgar`, the `development` branch is much further along than the `master` branch used by the `cli`. If you are interested in contributing, grab the slack link from the README of vulgar, and drop in to say hi. :)
